# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rontgen < Formula
  desc ""
  homepage "https://github.com/yonedash/Rontgen"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.0.0/Rontgen_Darwin_x86_64.tar.gz"
      sha256 "97fe69d67d723766623392b6d8a99bbfc45fc4f8c19edecc0a7f8f31b8539884"

      def install
        bin.install "rn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.0.0/Rontgen_Darwin_arm64.tar.gz"
      sha256 "9c2af91547ef2c5c842cc2581db031e9b2e7e40b10159a0f9277af35164c5a94"

      def install
        bin.install "rn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.0.0/Rontgen_Linux_arm64.tar.gz"
      sha256 "5b3d331f987b4868d3b491ba3b628d32005e0b861cbef749b2ac1c3925c8c1bd"

      def install
        bin.install "rn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.0.0/Rontgen_Linux_x86_64.tar.gz"
      sha256 "03f2062c357c804034375208e55e87cad032df9b034896d5805c15dcf00c47a8"

      def install
        bin.install "rn"
      end
    end
  end
end
