# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rontgen < Formula
  desc ""
  homepage "https://github.com/yonedash/Rontgen"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.2.0/Rontgen_Darwin_arm64.tar.gz"
      sha256 "fe8ae89eecfa539299cdd2e0351b2f5685055db8a70e24f33054bf20b8da5e51"

      def install
        bin.install "rn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.2.0/Rontgen_Darwin_x86_64.tar.gz"
      sha256 "e7bd7d6639885d9e1068a819336f2a724f195b5ce07afc6efc3e2a9fa99e79a2"

      def install
        bin.install "rn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.2.0/Rontgen_Linux_arm64.tar.gz"
      sha256 "33611dbab6ce9fe5985f9752c8759a36349fa2ffc45c21ef91f7bd3f2b625dd0"

      def install
        bin.install "rn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YONEDASH/Rontgen/releases/download/v1.2.0/Rontgen_Linux_x86_64.tar.gz"
      sha256 "f9eebab0f57932032e1086375dd8d2e9102ae9e37671541187e79cdbc4092052"

      def install
        bin.install "rn"
      end
    end
  end
end
